apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: teardown
spec:
  params:
    - name: NS
      type: string
      description: Namespace name to release
    - name: NS_REQUESTER
      type: string
      description: The name of the person/pipeline that requested the namespace
    - name: EPHEMERAL_ENV_PROVIDER_SECRET
      type: string
      default: ephemeral-env-provider
      description: "Secret for connecting to ephemeral env provider cluster"
  volumes:
    - name: artifacts
      emptyDir: {}
  steps:
    - name: collect-logs
      image: quay.io/redhat-user-workloads/rhtap-migration-tenant/bonfire-cicd-tools/cicd-tools:69cc1f37ab224fb74c872ac01fca70010fcf6627
      env:
        - name: OC_LOGIN_TOKEN
          valueFrom:
            secretKeyRef:
              name: $(params.EPHEMERAL_ENV_PROVIDER_SECRET)
              key: token
        - name: OC_LOGIN_SERVER
          valueFrom:
            secretKeyRef:
              name: $(params.EPHEMERAL_ENV_PROVIDER_SECRET)
              key: url
        - name: BONFIRE_BOT
          value: "true"
      onError: continue
      volumeMounts:
        - name: artifacts
          mountPath: /artifacts
      script: |
        #!/bin/bash
        set -ex
        
        echo "Connecting to the ephemeral namespace cluster"
        login.sh

        echo "Collecting logs"
        collect-logs.sh "$(params.NS)" /artifacts
